app:
  name: "project-camp-backend"
  env: "development"
  port: 3000

db:
  uri: ""
  name: ""

jwt:
  access_secret: ""
  refresh_secret: ""
  access_expiry_minutes: 15
  refresh_expiry_days: 7

smtp:
  host: ""
  port: 587
  username: ""
  password: ""
  from: ""

upload:
  dir: "public/images"
  max_size_mb: 5